/*
 * generated by Xtext 2.10.0
 */
package org.rmemory.xtext.entities.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.rmemory.xtext.entities.ui.internal.EntitiesActivator;

public class EntitiesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntitiesActivator.getInstance().getInjector("org.rmemory.xtext.entities.Entities");
	}

}
