/**
 * generated by Xtext 2.10.0
 */
package org.rmemory.xtext.entities;

import org.rmemory.xtext.entities.AbstractEntitiesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
