/*
 * generated by Xtext 2.10.0
 */
package org.rmemory.xtext.po.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PurchaseOrderUiModule extends AbstractPurchaseOrderUiModule {
}
