/*
 * generated by Xtext 2.10.0
 */
package org.rmemory.xtext.po.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PurchaseOrderStandaloneSetup extends PurchaseOrderStandaloneSetupGenerated {

	def static void doSetup() {
		new PurchaseOrderStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
